package ason

// Writer is the output side. Its core is the "lazy level":
// entering a container only registers it, without writing the opening bracket; the first write inside opens it (and every
// unopened ancestor). If it was never opened by the time it closes, nothing is written: a dropped element leaves no trace.
//
// Commas are handled by Key/Elem automatically, so protocol code never cares about output order; this is where "fields in any order" lands in the implementation.
type Writer struct {
	buf    []byte
	frames []wframe
	hint   int  // size handed over last time: the next buffer is reserved by it, one allocation per chunk
	fixed  bool // buf belongs to the caller (SetOutBuffer): never released, never replaced

	// get / put, when set (Transformer.SetBufferPool), lend buf instead of the writer keeping one: it is taken when
	// there is output to write and handed back once the sink has the bytes in it.
	get func(n int) []byte
	put func(b []byte)

	// Accounting for "this Feed produced exactly the bytes it was given" (Transformer.Unchanged).
	// passed counts bytes handed straight through from the input chunk; touched is set by every other
	// way of writing — generated bytes, separators, brackets, held-back whitespace. Both reset per chunk.
	passed  int
	touched bool
	base    int // len(buf) when the current Write started: non-zero means output was carried over from earlier chunks

	// Virtual output: while a chunk only passes bytes through, nothing is copied — the writer just counts how
	// far into the input it has got. The first byte that is not a straight pass-through ends the run: it goes to the
	// sink whole when flushRun is set and it is large enough to be worth a hand-over, and is copied into the buffer
	// otherwise; either way the writer goes back to the normal buffer. A chunk that never materialises costs no copy
	// at all: Out() hands back a slice of the caller's input, and with a sink the run leaves as a view of it.
	vp    []byte
	vfrom int // start of the run still held: the run is vp[vfrom:vlen], and flushRun moves vfrom forward
	vlen  int
	virt  bool

	// flushRun, when set, takes output that is final instead of it being copied: the engine sets it once the
	// transformer has committed and a sink is there to take the bytes. A chunk that is mostly forwarded verbatim then
	// never has a copy of itself made, wherever its rewrites fall -- what is passing through goes out as a view of
	// the input and only the generated bytes between the runs are ever copied.
	flushRun func(b []byte)
}

// flushRunMin is the size from which a pass-through run is handed to the sink rather than copied. Handing one over
// costs a sink call -- a host call, where the sink writes to a proxy's body -- and copying costs the bytes, so the
// small runs of a document that is rewritten throughout stay in the buffer and leave in one piece per chunk, while a
// large one (a whole body delivered at once, a long value) is never copied at all.
//
// Measured on a gateway with 70KB bodies delivered in one piece -- the load where the extra sink calls could have cost
// more than the copy they save -- this value does not lose anything: paired runs alternating the two builds gave 657
// and 672 requests/s with the write-through against 639 and 619 without it, the same CPU per request, and a steadier
// p99. Raise it only with a measurement that shows the opposite.
const flushRunMin = 16 << 10

type wframe struct {
	key    string // key written first when the level opens; "" = array element or root
	raw    []byte // when non-empty, used instead of "key": when opening (keeps the original whitespace) / whitespace before an element
	isArr  bool
	opened bool
	n      int    // number of children written
	trail  []byte // original whitespace after the previous child and before its comma: written before the next separator (fidelity)
}

// Level is the current level number (root = 0).
func (w *Writer) Level() int { return len(w.frames) - 1 }

func (w *Writer) push(key string, raw []byte, isArr bool) {
	nf := wframe{key: key, isArr: isArr}
	if n := len(w.frames); n < cap(w.frames) { // reuse the raw storage left in the slot
		nf.raw = append(w.frames[:n+1][n].raw[:0], raw...)
	} else {
		nf.raw = append([]byte(nil), raw...)
	}
	w.frames = append(w.frames, nf)
}

// reserve reserves the buffer by the size handed over last time when it is empty, avoiding repeated growth within one chunk.
func (w *Writer) reserve(n int) {
	if w.fixed {
		return // caller-owned buffer: already sized, never reallocated here
	}
	if cap(w.buf) == 0 {
		if n < w.hint { // hint is what the buffer may have to hold: one allocation covers the whole chunk
			n = w.hint
		}
		if n < 64 {
			n = 64
		}
		if w.get != nil {
			w.buf = w.get(n)[:0]
			return
		}
		w.buf = make([]byte, 0, n)
	}
}

// take borrows a buffer before output is appended, when the writer has none and buffers are lent.
func (w *Writer) take() {
	if cap(w.buf) == 0 && w.get != nil && !w.fixed {
		w.reserve(0)
	}
}

// pop closes the current level; nothing is written if it never opened. closeWs is the original whitespace before the closing bracket.
func (w *Writer) pop(closeWs []byte) {
	l := len(w.frames) - 1
	if w.frames[l].opened {
		w.touched = true
		w.materialise()
		w.buf = append(w.buf, closeWs...)
		if w.frames[l].isArr {
			w.buf = append(w.buf, ']')
		} else {
			w.buf = append(w.buf, '}')
		}
	}
	w.frames = w.frames[:l]
}

func (w *Writer) ensureOpen(level int) {
	f := &w.frames[level]
	if f.opened {
		return
	}
	w.touched = true
	w.materialise()
	if level > 0 {
		w.ensureOpen(level - 1)
		w.sep(level - 1)
		switch {
		case len(f.raw) > 0:
			w.buf = append(w.buf, f.raw...)
		case f.key != "":
			w.buf = append(w.buf, '"')
			w.buf = append(w.buf, f.key...)
			w.buf = append(w.buf, '"', ':')
		}
	}
	if f.isArr {
		w.buf = append(w.buf, '[')
	} else {
		w.buf = append(w.buf, '{')
	}
	f.opened = true
}

func (w *Writer) sep(level int) {
	w.take() // the callers append right after it, some without anything else having taken a buffer first
	f := &w.frames[level]
	if f.n > 0 || len(f.trail) > 0 {
		w.touched = true
		w.materialise()
	}
	if f.n > 0 {
		w.buf = append(w.buf, f.trail...)
		w.buf = append(w.buf, ',')
	}
	f.trail = f.trail[:0]
	f.n++
}

// trailWs records the original whitespace between the previous value of the current level and its comma (called when a dispatch frame reads a comma).
func (w *Writer) trailWs(ws []byte) {
	if l := len(w.frames) - 1; l >= 0 {
		w.frames[l].trail = append(w.frames[l].trail[:0], ws...)
	}
}

// CanWriteAt reports whether level can be written to directly: every level above it is still unopened.
func (w *Writer) CanWriteAt(level int) bool {
	for l := level + 1; l < len(w.frames); l++ {
		if w.frames[l].opened {
			return false
		}
	}
	return true
}

// Opened reports whether level has been opened.
func (w *Writer) Opened(level int) bool {
	return level >= 0 && level < len(w.frames) && w.frames[level].opened
}

// KeyAt writes "name": at level, handling the comma and the opening of ancestor levels.
// Returns false and writes nothing when an opened level exists above it.
func (w *Writer) KeyAt(level int, name string) bool {
	if !w.CanWriteAt(level) {
		return false
	}
	w.ensureOpen(level)
	w.sep(level)
	w.buf = append(w.buf, '"')
	w.buf = append(w.buf, name...)
	w.buf = append(w.buf, '"', ':')
	return true
}

// KeyRawAt is KeyAt with the key written from its raw bytes (whitespace and colon included).
func (w *Writer) KeyRawAt(level int, raw []byte) bool {
	if !w.CanWriteAt(level) {
		return false
	}
	w.ensureOpen(level)
	w.sep(level)
	w.buf = append(w.buf, raw...)
	return true
}

// KeyRaw acts on the current level.
func (w *Writer) KeyRaw(raw []byte) { w.KeyRawAt(w.Level(), raw) }

// ElemRawAt is ElemAt that also writes the original whitespace before the element.
func (w *Writer) ElemRawAt(level int, ws []byte) bool {
	if !w.CanWriteAt(level) {
		return false
	}
	w.ensureOpen(level)
	w.sep(level)
	w.buf = append(w.buf, ws...)
	return true
}

// ElemAt starts an element at level (an array): only the comma and the opening are handled.
func (w *Writer) ElemAt(level int) bool {
	if !w.CanWriteAt(level) {
		return false
	}
	w.ensureOpen(level)
	w.sep(level)
	return true
}

// Key / Elem act on the current level.
func (w *Writer) Key(name string) { w.KeyAt(w.Level(), name) }
func (w *Writer) Elem()           { w.ElemAt(w.Level()) }

// PushObj / PushArr / Pop let a protocol build levels on the output side itself, for "one input container lands in several nested
// output levels" (the native Qwen protocol putting messages into input.messages, say). Used together with Enter().Flat();
// the protocol is responsible for the matching Pop at the same callback level.
func (w *Writer) PushObj(key string) { w.push(key, nil, false) }
func (w *Writer) PushArr(key string) { w.push(key, nil, true) }
func (w *Writer) Pop()               { w.pop(nil) }

// Open forces the current level open (when an empty container must be materialized, e.g. the output must contain "content":[]).
func (w *Writer) Open() { w.ensureOpen(w.Level()) }

// Raw appends bytes verbatim. The caller is responsible for them appearing at a syntactically valid position.
func (w *Writer) Raw(b []byte) {
	w.touched = true
	w.materialise()
	w.reserve(len(b))
	w.buf = append(w.buf, b...)
}
func (w *Writer) RawString(s string) { w.touched = true; w.materialise(); w.buf = append(w.buf, s...) }
func (w *Writer) Byte(c byte)        { w.touched = true; w.materialise(); w.buf = append(w.buf, c) }

// passthroughAt appends bytes from the current input chunk (engine-internal): p[from:to].
// It is the only write that does not mark the output as changed, and while the run is still contiguous from
// the start of the chunk it copies nothing at all.
func (w *Writer) passthroughAt(p []byte, from, to int) {
	if w.virt {
		if from == w.vlen {
			w.vlen = to
			w.passed += to - from
			return
		}
		w.materialise() // a gap: something before this was dropped, so the output is not the input any more
	}
	if w.flushRun != nil && to-from >= flushRunMin {
		// A pass-through segment this size is worth not copying, and pass-through resuming means whatever was
		// written before it is complete: past the commit point it can go, and the writer goes back to counting.
		if len(w.buf) > 0 {
			w.flushRun(w.buf)
			w.buf = w.buf[:0]
		}
		w.vp, w.vfrom, w.vlen, w.virt = p, from, to, true
		w.passed += to - from
		return
	}
	w.reserve(to - from)
	w.buf = append(w.buf, p[from:to]...)
	w.passed += to - from
}

// materialise copies the pass-through run collected so far into the real buffer.
func (w *Writer) materialise() {
	if !w.virt {
		w.take()
		return
	}
	w.virt = false
	if n := w.vlen - w.vfrom; n > 0 {
		if w.flushRun != nil && n >= flushRunMin && len(w.buf) == 0 {
			// A run worth handing over: it goes to the sink instead of into the buffer the writes after it need,
			// so a rewrite at the end of a large chunk no longer copies everything that came before it.
			w.flushRun(w.vp[w.vfrom:w.vlen])
			w.vfrom = w.vlen
			w.take()
			return
		}
		w.reserve(n + 64)
		w.buf = append(w.buf, w.vp[w.vfrom:w.vlen]...)
		return
	}
	w.take()
}

// startChunk resets the per-chunk accounting; the chunk can stay virtual only when nothing is carried over.
func (w *Writer) startChunk(p []byte) {
	w.passed, w.touched, w.base = 0, false, len(w.buf)
	w.vp, w.vfrom, w.vlen, w.virt = p, 0, 0, len(w.buf) == 0
}

// AppendWith writes whatever f appends to the output buffer, without a buffer of the caller's own in between: f is
// handed the buffer itself and returns it grown. For output that is produced by an encoder rather than copied --
// base64 of a fetched image, say -- where the intermediate would be as large as the output and allocated per slice.
func (w *Writer) AppendWith(f func(dst []byte) []byte) {
	w.touched = true
	w.materialise()
	w.buf = f(w.buf)
}

// release drops the reference to the chunk the caller handed in. Between two Writes nothing reads it, and a scan that
// pauses there -- waiting for a fetch, or for a field the header needs -- would otherwise keep that whole chunk alive
// for as long as it waits, once per stream. Called when what the chunk produced has already been taken.
func (w *Writer) release() {
	w.vp, w.vfrom, w.vlen, w.virt = nil, 0, 0, false
}

// output returns what this chunk produced: the untouched input run when still virtual, the buffer otherwise.
func (w *Writer) output() []byte {
	if w.virt {
		return w.vp[w.vfrom:w.vlen]
	}
	return w.buf
}

// JSONString writes a quoted, escaped JSON string.
func (w *Writer) JSONString(s string) {
	w.touched = true
	w.materialise()
	w.buf = AppendJSONString(w.buf, s)
}

// Int writes a decimal integer.
func (w *Writer) Int(n int) { w.touched = true; w.materialise(); w.buf = appendInt(w.buf, n) }

// Len is the number of output bytes not yet taken.
func (w *Writer) Len() int { return len(w.buf) }
